# baseURL = "https://your_domain.com/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Find Draggor on the Internet"
# copyright = "Copy, _right?_ :thinking_face:"
description = "These are the places I have accounts"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Draggor"
  headline = "A Demon on the Internet"
  image = "draggor-icon.jpg"  # path relative to static directory

  links = [
    { email = { href="mailto:draggor@gmail.com", icon="envelope", text="Email (draggor@gmail.com)" } },
    { link = { href="https://draggor.me", text="https://draggor.me" } },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { bandcamp = "https://username.bandcamp.com" },
    { bluesky = { href="https://bsky.app/profile/draggor.me", text="Bluesky (@draggor.me)" } },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/invitecode" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    { github = { href="https://github.com/draggor", text="GitHub (draggor)" } },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://last.fm/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    { mastodon = { href="https://meow.social/@draggor", text="Mastodon (@draggor@meow.social)" } },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    { reddit = { href="https://reddit.com/user/draggor", text="Reddit (draggor)" } },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { spotify = "https://spotify.com/user/username" },
    # { stack-exchange = "https://stackexchange.com/users/userid/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    { telegram = { href="https://t.me/draggor", text="Telegram (@draggor)" } },
    # { threads = "https://threads.com/username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    { twitch = { href="https://twitch.tv/draggordotme", text="Twitch (DraggorDotMe)" } },
    # { twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { x = "https://x.com/username" },
    { youtube = { href="https://youtube.com/@DraggorDotMe", text="YouTube (@DraggorDotMe)" } },
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
